// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usb_device.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_usb_5fdevice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_usb_5fdevice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_usb_5fdevice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_usb_5fdevice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_usb_5fdevice_2eproto;
class UsbDeviceState;
struct UsbDeviceStateDefaultTypeInternal;
extern UsbDeviceStateDefaultTypeInternal _UsbDeviceState_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::UsbDeviceState* Arena::CreateMaybeMessage<::UsbDeviceState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class UsbDeviceState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UsbDeviceState) */ {
 public:
  inline UsbDeviceState() : UsbDeviceState(nullptr) {}
  ~UsbDeviceState() override;
  explicit constexpr UsbDeviceState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UsbDeviceState(const UsbDeviceState& from);
  UsbDeviceState(UsbDeviceState&& from) noexcept
    : UsbDeviceState() {
    *this = ::std::move(from);
  }

  inline UsbDeviceState& operator=(const UsbDeviceState& from) {
    CopyFrom(from);
    return *this;
  }
  inline UsbDeviceState& operator=(UsbDeviceState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UsbDeviceState& default_instance() {
    return *internal_default_instance();
  }
  static inline const UsbDeviceState* internal_default_instance() {
    return reinterpret_cast<const UsbDeviceState*>(
               &_UsbDeviceState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UsbDeviceState& a, UsbDeviceState& b) {
    a.Swap(&b);
  }
  inline void Swap(UsbDeviceState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UsbDeviceState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UsbDeviceState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UsbDeviceState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UsbDeviceState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const UsbDeviceState& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UsbDeviceState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UsbDeviceState";
  }
  protected:
  explicit UsbDeviceState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConfigurationValueFieldNumber = 1,
    kRemoteWakeupFieldNumber = 2,
  };
  // uint32 configuration_value = 1;
  void clear_configuration_value();
  uint32_t configuration_value() const;
  void set_configuration_value(uint32_t value);
  private:
  uint32_t _internal_configuration_value() const;
  void _internal_set_configuration_value(uint32_t value);
  public:

  // uint32 remote_wakeup = 2;
  void clear_remote_wakeup();
  uint32_t remote_wakeup() const;
  void set_remote_wakeup(uint32_t value);
  private:
  uint32_t _internal_remote_wakeup() const;
  void _internal_set_remote_wakeup(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:UsbDeviceState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t configuration_value_;
  uint32_t remote_wakeup_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_usb_5fdevice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UsbDeviceState

// uint32 configuration_value = 1;
inline void UsbDeviceState::clear_configuration_value() {
  configuration_value_ = 0u;
}
inline uint32_t UsbDeviceState::_internal_configuration_value() const {
  return configuration_value_;
}
inline uint32_t UsbDeviceState::configuration_value() const {
  // @@protoc_insertion_point(field_get:UsbDeviceState.configuration_value)
  return _internal_configuration_value();
}
inline void UsbDeviceState::_internal_set_configuration_value(uint32_t value) {
  
  configuration_value_ = value;
}
inline void UsbDeviceState::set_configuration_value(uint32_t value) {
  _internal_set_configuration_value(value);
  // @@protoc_insertion_point(field_set:UsbDeviceState.configuration_value)
}

// uint32 remote_wakeup = 2;
inline void UsbDeviceState::clear_remote_wakeup() {
  remote_wakeup_ = 0u;
}
inline uint32_t UsbDeviceState::_internal_remote_wakeup() const {
  return remote_wakeup_;
}
inline uint32_t UsbDeviceState::remote_wakeup() const {
  // @@protoc_insertion_point(field_get:UsbDeviceState.remote_wakeup)
  return _internal_remote_wakeup();
}
inline void UsbDeviceState::_internal_set_remote_wakeup(uint32_t value) {
  
  remote_wakeup_ = value;
}
inline void UsbDeviceState::set_remote_wakeup(uint32_t value) {
  _internal_set_remote_wakeup(value);
  // @@protoc_insertion_point(field_set:UsbDeviceState.remote_wakeup)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_usb_5fdevice_2eproto
